// code messages
export enum Codemessages {
    success = 'Success',
    created = 'Created',
    deleted = 'Deleted',
    updated = 'Updated', 
    user_exist = 'You already registered with this email. Please log in with proper credentials OR contact the admin.',
    user_create = 'Your Registration successfully', 
    user_welcome = 'Welcome Back',
    invalid_otp = 'Invalid OTP ',
    otp_verified = 'OTP Verified Successfully',
    otp_expired = 'OTP is Expired',
    otp_resend = 'OTP Resend Successfully',
    otp_success = 'OTP sent Successfully',
    user_deactivate= 'This email account not registered. Please register',
    invalid_password= 'Incorrect password.',
    login_success = 'User LoggedIn Successfully',
    invalid_user = "Couldn't find an account associated with this email. Please register for an account.",
    forgot_password = 'A reset email has been sent! Please check your email.',
    password_success = 'Password changed',
    email_notVerified= 'This email account is not registered. Please register',
    mail_failure = 'A Timeout Error occurs for Email Actions, Please try Some other Time',
    email_exist ='Email already registered.',
    email_available = 'Email is Available',
    invalid_email = 'Sorry. We do not recognize this email',
    provider_exist = 'You already registered with this google Id. Please log in through google',
    email_invalid = 'Invalid Email',
    fpwd_witjout_verify = 'Please Verify your Email to Reset the Password',
    account_exist = 'Account existing with this email. Activate the account by using verification email sent to you earlier',
}