
// code messages
export enum Codemessages {
    success = 'Success',
    created = 'Created',
    deleted = 'Deleted',
    updated = 'Updated', 
    user_exist = 'You already registered with this email. Please log in with proper credentials OR contact the admin.',
    user_create = 'Your Registration successfully', 
    user_welcome = 'Welcome Back',
    invalid_otp = 'Invalid OTP ',
    otp_verified = 'OTP Verified Successfully',
    otp_resend = 'OTP Resend Successfully',
    user_deactivate= 'Your account is temporarily deactivated. Please contact the administrator.',
    invalid_password= 'Incorrect password.',
    login_success = 'User LoggedIn Successfully',
    invalid_user = 'User Does not Exist',
    forgot_password = 'A reset email has been sent! Please check your email.',
    password_success = 'Password changed',
    page_create = 'Page created successfully.',
    page_update = 'Page updated successfully.',
    page_status = 'Status changed successfully',
    page_exist = 'This page was already created under this Name',
    page_detail = 'detail getting successfully',
    page_publish = 'Congratulations! Your Page is published.',
    invalid_page = 'Invalid page data',
    status_change = 'Status changed successfully.',
    event_create = 'Event Created success',
    event_update = 'Event Updated Success',
    event_detail = 'Event details getting Success',
    all_events = 'All events details listed success',
    event_exist = 'Event already exist under this name',
    invalid_event = 'Event does not exist',
    page_delete = 'Page deleted successfully.',
    fundraiser_create = 'Fundraiser created successfully',
    fundraiser_get = 'Fundraiser(s) found successfully',
    fundraiser_get_fail = 'Failed getting fundraiser(s)',
    fundraiser_update = 'Fundraiser updated successfully',
    fundraiser_details = 'Fundraiser details grabbed successfully',
    fundraiser_create_fail = 'Error creating fundraiser',
    invalid_fundraiser = 'Fundraiser not found',
    fundraiser_donation = 'Donation added successfully',
    organizations_list = 'Organizations list fetched successfully'
}